FROM python:3.7
RUN apt-get update
RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip
COPY requirements.txt /
RUN pip3 install -r requirements.txt
COPY src /src
ENTRYPOINT cd /src && streamlit run uber_pickup.py